const sidebars = {
  terminologyDesignSideBar: [
    { label: 'On Terminology Design',
      link: {type: 'doc', id: 'overview'},
      type: 'category',
      items: [
        { type: 'autogenerated', dirName: 'overview' },
      ]
    },
    { label: 'Methods',
      link: {type: 'doc', id: 'methods'},
      type: 'category',
      items: [
        { type: 'autogenerated', dirName: 'methods' },
      ]
    },
    { label: 'Backgrounds',
//    link: {type: 'doc', id: 'backgrounds'},
      type: 'category',
      items: [
        { type: 'autogenerated', dirName: 'backgrounds' },
      ]
    },
    { type: 'doc', id: 'tev2-glossary'},
    // { type: 'category',
    //   label: 'Glossary',
    //   items: [ { type: 'autogenerated', dirName: 'terms' } ]
    // },
    { label: 'Backlog / Work-in-Progress', type: 'doc', id: 'backlog' },
  ],
};

module.exports = sidebars;
