const sidebars = {
  terminologyDesignSideBar: [
    { type: 'category',
      label: 'On Terminology Design',
      link: {type: 'doc', id: 'overview'},
      items: [
        { type: 'autogenerated', dirName: 'overview' },
      ]
    },
    { type: 'category',
      label: 'Methods',
      link: {type: 'doc', id: 'methods'},
      items: [
        { type: 'autogenerated', dirName: 'methods' },
      ]
    },
    { type: 'category',
      label: 'Backgrounds',
//      link: {type: 'doc', id: 'backgrounds'},
      items: [
        { type: 'autogenerated', dirName: 'backgrounds' },
      ]
    },
    { type: 'category',
      label: 'Glossary',
      items: [ { type: 'autogenerated', dirName: 'terms' } ]
    },
    { type: 'doc', label: 'Backlog / Work-in-Progress', id: 'backlog'
    },
  ],
};

module.exports = sidebars;
